title: Syed Inzamam Ul Hassan
logo: /main/DP.png{: style="border-radius: 50%; width: 150px;" }

# Syed Inzamam Ul Hassan
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
